'''
Created on 25.11.2014

@author: jk
'''
ID_MAX = 200
DOOR_OPEN_TIME = 3  #in Sekunden
WAIT_FOR_USER_INTERACTION = 10  #in Sekunden

ACK = 0
NACK = -1
ID_ERROR = -2
LENGTH_ERROR = -3
PACKET_HEADER_ERROR = -4
CHECKSUM_ERROR = -5
SERIAL_PORT_ERROR = -6
DUPLICATED_ID_ERROR = -7
SERIAL_PORT_TIMEOUT = -8

NACK_TIMEOUT = -1
NACK_INVALID_BAUDRATE = -2
NACK_INVALIDE_POS = -3
NACK_IS_NOT_USED = -4
NACK_IS_ALREDY_USED = -5
NACK_COMM_ERR = -6
NACK_VERIVY_FAILED = -7
NACK_IDENTIFY_FAILD = -8
NACK_DB_IS_FULL = -9
NACK_DB_IS_EMPTY = -10
NACK_TURN_ERR = -11
NACK_BAD_FINGER = -12
NACK_ENROLL_FAILED = -13
NACK_IS_NOT_SUPPORTED = -14
NACK_DEV_ERR = -15
NACK_CAPTURE_CANCELED = -16
NACK_INVALID_PARAM = -17
NACK_FINGER_IS_NOT_PRESSED = -18
COMMAND_PACK_ERROR = -19
DATA_PACK_ERROR = -20

HEADER = 6
INFO = 24
TEMPLATE = 498
IMAGE = 52116
QVGA_IMAGE = 19200